const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

const supabaseUrl = 'https://xnhvjttfeuztvaeuqquc.supabase.com';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuaHZqdHRmZXV6dHZhZXVxcXVjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTc0MDM3NSwiZXhwIjoyMDg3MzE2Mzc1fQ.NPnRDMvksk_nmi_2igufstc5vaTvvLRxRoGrtNUNHOo';

const supabase = createClient(supabaseUrl, supabaseKey);

async function seed() {
    console.log('🌱 Seeding Careers...');
    const { error: e1 } = await supabase.from('career_profiles').upsert([
        { title: 'Software Engineer', slug: 'software-engineer', icon: '💻', stream: 'Technology', summary: 'Build the digital products that power the modern world. Software engineers design, develop, and maintain applications across web, mobile, and backend systems.', avg_salary: '₹8L – ₹40L per year', study_duration: '4 Years (B.Tech)', growth_outlook: 'Excellent — 25% growth by 2030', skills_needed: ['Python', 'JavaScript', 'Data Structures', 'System Design', 'Git'], top_companies: ['Google', 'Microsoft', 'Amazon', 'Flipkart', 'Infosys'], view_count: 0 },
        { title: 'Data Scientist', slug: 'data-scientist', icon: '📊', stream: 'Technology', summary: 'Extract insights from massive datasets to guide business decisions. Data Scientists work at the intersection of statistics, programming, and domain expertise.', avg_salary: '₹10L – ₹50L per year', study_duration: '4 Years (B.Tech / B.Sc)', growth_outlook: 'Very High — AI boom driving demand', skills_needed: ['Python', 'R', 'Machine Learning', 'SQL', 'TensorFlow'], top_companies: ['Meta', 'Netflix', 'Walmart Labs', 'Ola', 'Zomato'], view_count: 0 },
        { title: 'Doctor (MBBS)', slug: 'doctor-mbbs', icon: '🩺', stream: 'Medicine', summary: 'Diagnose and treat patients across a wide range of medical conditions. One of the most respected and impactful careers in India.', avg_salary: '₹6L – ₹30L per year', study_duration: '5.5 Years (MBBS + Internship)', growth_outlook: 'Stable — Always in demand', skills_needed: ['Biology', 'Clinical Skills', 'Patient Communication', 'Anatomy', 'Pharmacology'], top_companies: ['AIIMS', 'Private Hospitals', 'WHO', 'PHC'], view_count: 0 },
        { title: 'Chartered Accountant', slug: 'chartered-accountant', icon: '📈', stream: 'Finance', summary: 'Manage financial records, audits, and taxation for individuals and corporations. CA is one of the most prestigious professional qualifications in India.', avg_salary: '₹7L – ₹35L per year', study_duration: '4-5 Years (CA Course)', growth_outlook: 'High — Essential for every business', skills_needed: ['Accounting', 'Taxation', 'Financial Reporting', 'Auditing', 'Tally'], top_companies: ['Deloitte', 'PwC', 'KPMG', 'Big Corporates', 'Self Practice'], view_count: 0 },
        { title: 'Civil Services Officer (IAS/IPS)', slug: 'civil-services-ias-ips', icon: '🏛️', stream: 'Government', summary: 'Serve the nation through public administration, policy implementation, and governance. UPSC Civil Services is the pinnacle of competitive exams in India.', avg_salary: '₹56K – ₹2.5L per month', study_duration: '2-3 Years of Preparation', growth_outlook: 'Stable — Government job with lifetime security', skills_needed: ['General Studies', 'Essay Writing', 'CSAT', 'Optional Subject', 'Interview Skills'], top_companies: ['Government of India', 'State Governments', 'PSUs'], view_count: 0 },
        { title: 'Product Manager', slug: 'product-manager', icon: '🚀', stream: 'Technology', summary: 'Bridge the gap between users, business, and engineering to ship products that matter. PMs own the vision and roadmap of a product.', avg_salary: '₹15L – ₹60L per year', study_duration: '4 Years (Any Degree + MBA preferred)', growth_outlook: 'High — Every tech startup needs PMs', skills_needed: ['Product Thinking', 'Data Analysis', 'User Research', 'Roadmapping', 'Communication'], top_companies: ['Google', 'Razorpay', 'PhonePe', 'CRED', 'Swiggy'], view_count: 0 },
        { title: 'Architect', slug: 'architect', icon: '🏗️', stream: 'Design & Construction', summary: 'Design buildings and spaces that shape how people live, work, and play. Architects combine creativity, technical knowledge, and an understanding of human needs.', avg_salary: '₹5L – ₹25L per year', study_duration: '5 Years (B.Arch)', growth_outlook: 'Steady — Driven by real estate & infrastructure boom', skills_needed: ['AutoCAD', 'Structural Design', '3D Modeling', 'Building Codes', 'Revit'], top_companies: ['Hafeez Contractor', 'CP Kukreja', 'Government PWD', 'Real Estate Firms'], view_count: 0 },
        { title: 'Graphic Designer', slug: 'graphic-designer', icon: '🎨', stream: 'Creative Arts', summary: 'Communicate ideas visually through branding, UI, marketing, and digital content. Graphic Designers are needed across every industry.', avg_salary: '₹3L – ₹18L per year', study_duration: '3-4 Years (B.Des / BFA)', growth_outlook: 'Good — Growing rapidly in the digital startup ecosystem', skills_needed: ['Adobe Photoshop', 'Figma', 'Illustrator', 'Typography', 'Brand Identity'], top_companies: ['Ogilvy', 'Dentsu', 'Startups', 'Freelance', 'Advertising Agencies'], view_count: 0 },
    ], { onConflict: 'slug' });
    if (e1) console.error('Careers error:', e1.message); else console.log('✅ Careers seeded');

    console.log('🌱 Seeding Courses...');
    const { error: e2 } = await supabase.from('courses').upsert([
        { title: 'Bachelor of Technology (B.Tech)', slug: 'btech', description: 'The most popular undergraduate engineering degree in India. Covers disciplines like CS, Mechanical, Civil, Electrical, and more.', duration: '4 Years', eligibility: '10+2 with PCM, 60%+ marks', type: 'Undergraduate Degree' },
        { title: 'Bachelor of Medicine and Surgery (MBBS)', slug: 'mbbs', description: 'The foundational medical degree required to practice as a doctor. Covers human anatomy, physiology, pathology, and clinical rotations.', duration: '5.5 Years (incl. Internship)', eligibility: '10+2 with PCB, NEET qualified', type: 'Undergraduate Degree' },
        { title: 'Master of Business Administration (MBA)', slug: 'mba', description: 'A postgraduate degree focused on leadership, management, finance, and strategy. Transforms graduates into business leaders.', duration: '2 Years', eligibility: 'Any Bachelors degree, CAT/GMAT', type: 'Postgraduate Degree' },
        { title: 'Bachelor of Commerce (B.Com)', slug: 'bcom', description: 'A versatile commerce degree covering accounting, taxation, business law, and economics. Common entry point for CA, CS or MBA aspirants.', duration: '3 Years', eligibility: '10+2 with Commerce stream preferred', type: 'Undergraduate Degree' },
        { title: 'Bachelor of Science in Data Science', slug: 'bsc-data-science', description: 'An emerging undergraduate program covering statistics, Python, machine learning, and AI. Offered by IITs, BITS, and leading private universities.', duration: '3-4 Years', eligibility: '10+2 with Mathematics, 60%+ marks', type: 'Undergraduate Degree' },
        { title: 'Bachelor of Design (B.Des)', slug: 'bdes', description: 'A creative undergraduate program covering product design, graphic design, or UX/UI design. Offered by NID and IITs.', duration: '4 Years', eligibility: '10+2 any stream, Design Aptitude Test required', type: 'Undergraduate Degree' },
        { title: 'Chartered Accountancy (CA)', slug: 'chartered-accountancy', description: 'One of India\'s most prestigious professional qualifications by ICAI. Split into Foundation, Intermediate, and Final levels.', duration: '4-5 Years', eligibility: '10+2 for Foundation / Graduation for Direct Entry', type: 'Professional Certification' },
        { title: 'B.Arch (Bachelor of Architecture)', slug: 'barch', description: 'A 5-year professional degree required to become a licensed architect in India. Combines studio design work with technical knowledge.', duration: '5 Years', eligibility: '10+2 with Mathematics, NATA qualified', type: 'Undergraduate Degree' },
    ], { onConflict: 'slug' });
    if (e2) console.error('Courses error:', e2.message); else console.log('✅ Courses seeded');

    console.log('🌱 Seeding Exams...');
    const { error: e3 } = await supabase.from('exams').upsert([
        { name: 'JEE Main', slug: 'jee-main', full_form: 'Joint Entrance Examination - Main', level: 'National', mode: 'Online CBT', description: 'The gateway examination for admission to NITs, IIITs, and other centrally funded technical institutions.', syllabus: 'Physics: Mechanics, Thermodynamics, Optics\nChemistry: Physical, Organic, Inorganic\nMathematics: Algebra, Calculus, Coordinate Geometry' },
        { name: 'JEE Advanced', slug: 'jee-advanced', full_form: 'Joint Entrance Examination - Advanced', level: 'National', mode: 'Online CBT', description: 'The most competitive engineering entrance exam in India, conducted by IITs. Only top 2.5 lakh JEE Main qualifiers are eligible.', syllabus: 'Physics, Chemistry, Mathematics at deeper conceptual level. Multi-concept and application based questions.' },
        { name: 'NEET UG', slug: 'neet-ug', full_form: 'National Eligibility cum Entrance Test - Undergraduate', level: 'National', mode: 'Offline OMR', description: 'Single national entrance test for MBBS, BDS, AYUSH admissions across India. Managed by NTA.', syllabus: 'Physics (20%), Chemistry (20%), Biology - Botany + Zoology (60%). Based on NCERT Class 11-12 syllabus.' },
        { name: 'CAT', slug: 'cat', full_form: 'Common Admission Test', level: 'National', mode: 'Online CBT', description: 'Premier MBA entrance exam for admission to IIMs and 1200+ B-schools. Conducted annually by one of the IIMs.', syllabus: 'Verbal Ability & Reading Comprehension (VARC)\nData Interpretation & Logical Reasoning (DILR)\nQuantitative Ability (QA)' },
        { name: 'UPSC CSE', slug: 'upsc-cse', full_form: 'UPSC Civil Services Examination', level: 'National', mode: 'Offline + Interview', description: 'India\'s toughest competitive exam for IAS, IPS, IFS recruitment. Three stages: Prelims, Mains, and Interview.', syllabus: 'Prelims: GS Paper I + CSAT\nMains: 9 papers (GS, Essay, Optional Subject)\nInterview: Personality Test (275 marks)' },
        { name: 'GATE', slug: 'gate', full_form: 'Graduate Aptitude Test in Engineering', level: 'National', mode: 'Online CBT', description: 'For M.Tech and Ph.D admissions at IISc/IITs. GATE score also used by PSUs like BHEL, ONGC, NTPC for recruitment.', syllabus: 'General Aptitude (15 marks) + Engineering Mathematics + Subject-specific paper (based on B.Tech stream)' },
        { name: 'NATA', slug: 'nata', full_form: 'National Aptitude Test in Architecture', level: 'National', mode: 'Online + Drawing', description: 'Primary entrance exam for B.Arch admission across India. Conducted by COA (Council of Architecture).', syllabus: 'Part A: Diagrammatic & Numerical Reasoning, Verbal\nPart B: Drawing test — 3D perception, imagination, architectural awareness' },
    ], { onConflict: 'slug' });
    if (e3) console.error('Exams error:', e3.message); else console.log('✅ Exams seeded');

    console.log('🌱 Seeding Colleges...');
    const { error: e4 } = await supabase.from('colleges').upsert([
        { name: 'Indian Institute of Technology Bombay', slug: 'iit-bombay', location: 'Mumbai, Maharashtra', type: 'Central University (IIT)', avg_package: '₹28 LPA (Average)', top_recruiters: 'Microsoft, Google, Goldman Sachs, DE Shaw, McKinsey', description: 'IIT Bombay is consistently ranked among the top 2 engineering institutes in India. Known for world-class research and exceptional placements.' },
        { name: 'Indian Institute of Technology Delhi', slug: 'iit-delhi', location: 'New Delhi', type: 'Central University (IIT)', avg_package: '₹26 LPA (Average)', top_recruiters: 'Samsung, Amazon, Qualcomm, BCG, Bain', description: 'IIT Delhi is the top-ranked engineering institute in India\'s capital. Renowned for cutting-edge research and strong industry connections.' },
        { name: 'AIIMS Delhi', slug: 'aiims-delhi', location: 'New Delhi', type: 'Central University (Medical)', avg_package: '₹12 LPA (Average)', top_recruiters: 'Government Hospitals, Research Institutions, WHO', description: 'AIIMS Delhi is the crown jewel of medical education in India. The most sought-after medical institution with the highest NEET cut-off.' },
        { name: 'Indian Institute of Management Ahmedabad', slug: 'iim-ahmedabad', location: 'Ahmedabad, Gujarat', type: 'Central University (IIM)', avg_package: '₹35 LPA (Average CTC)', top_recruiters: 'McKinsey, BCG, Bain, Goldman Sachs, Amazon', description: 'IIMA is India\'s top business school and globally recognized. The PGP (MBA) program is among the most selective in the world.' },
        { name: 'NIT Trichy', slug: 'nit-trichy', location: 'Tiruchirappalli, Tamil Nadu', type: 'Central University (NIT)', avg_package: '₹18 LPA (Average)', top_recruiters: 'Samsung, Qualcomm, TCS, Infosys, Texas Instruments', description: 'NIT Trichy is the top-ranked NIT in India offering exceptional engineering education. Known for high placement in Tier-1 companies.' },
        { name: 'Delhi University (DU)', slug: 'delhi-university', location: 'New Delhi', type: 'Central University', avg_package: '₹8 LPA (Average)', top_recruiters: 'Big 4 Firms, Media Companies, Government, Startups', description: 'Delhi University is one of the most prestigious central universities in India, renowned for undergraduate programs. SRCC, Hindu, LSR are highly coveted colleges.' },
        { name: 'Christ University', slug: 'christ-university', location: 'Bengaluru, Karnataka', type: 'Deemed University', avg_package: '₹6 LPA (Average)', top_recruiters: 'Accenture, Wipro, Capgemini, Startups, Media', description: 'A leading deemed university in South India known for diverse programs in law, management, science, and arts. Strong focus on holistic development.' },
        { name: 'Manipal Institute of Technology', slug: 'manipal-institute-of-technology', location: 'Manipal, Karnataka', type: 'Deemed University (Private)', avg_package: '₹14 LPA (Average)', top_recruiters: 'Amazon, Microsoft, Infosys, Cognizant, HDFC', description: 'MIT Manipal is one of India\'s top private engineering institutes. Exceptional placement record and strong industry collaborations.' },
    ], { onConflict: 'slug' });
    if (e4) console.error('Colleges error:', e4.message); else console.log('✅ Colleges seeded');

    console.log('\n🎉 All done! Check your Explore pages now.');
}

seed().catch(console.error);
